<?php
/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2018-3-22
 * Time: 18:04
 */

namespace app\Models\Business;
use Server\CoreBase\Model;

class BaseBusiness extends Model
{

    /**
     * 装置所有model
     * @var
     */
    protected $Model;

    /**
     * 装置所有数据
     * @var
     */
    protected $Data;

    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
    }
}